// packages/widgets/src/cart-contents/vue/CartContents.vue
<script setup lang="ts">
import NumberFlow from '@number-flow/vue'
import { PhBag, PhCalendarBlank } from '@phosphor-icons/vue'
import { computed } from 'vue'

import {
  type CartDetails,
  currencyPrefix,
  formatCurrency,
  formatDayHeader,
  groupEventsByDay
} from '../../cart'
import CartEmptyState from './CartEmptyState.vue'
import CartEventGroup from './CartEventGroup.vue'

const PRICE_FORMAT = { minimumFractionDigits: 2 }

const props = withDefaults(
  defineProps<{
    cart: CartDetails
    onNavigate: (href: string) => void
    /** App-specific browse target for the empty state (design finding #4). */
    browseHref: string
    /** Pre-validated checkout URL; null disables the CTA (unsafe extrasUrl). */
    checkoutUrl: string | null
    locale: string
    currency: string
    /**
     * For standalone `/cart`-style pages: make the root a fill-height column,
     * pin the footer to the bottom for short carts (mt-auto), and centre the
     * empty state. Leave unset inside the drawer, which sizes its own panel.
     */
    fillHeight?: boolean
    /** Skip the Total / fees / Checkout footer (the drawer renders its own). */
    hideFooter?: boolean
    /** True while a cart-wide remove is in flight — locks the per-event trash. */
    busy?: boolean
  }>(),
  { fillHeight: false, hideFooter: false }
)

const emit = defineEmits<{
  removeEvent: [eventId: string]
}>()

const ticketCount = computed(() =>
  props.cart.events.reduce(
    (sum, event) =>
      sum + event.tickets.reduce((tSum, t) => tSum + t.quantity, 0),
    0
  )
)
const isEmpty = computed(() => ticketCount.value === 0)

const dayGroups = computed(() => groupEventsByDay(props.cart.events))
const totalBookingFees = computed(() =>
  props.cart.events.reduce((sum, event) => sum + event.bookingFees, 0)
)
const pricePrefix = computed(() => currencyPrefix(props.locale, props.currency))

function dayHeader(key: string): string {
  return formatDayHeader(key, { locale: props.locale })
}
function money(amount: number): string {
  return formatCurrency(amount, {
    locale: props.locale,
    currency: props.currency
  })
}
function onCheckout() {
  if (props.checkoutUrl) props.onNavigate(props.checkoutUrl)
}

// Collapse height + fade on removal, mirroring the React skin's AnimatePresence
// exit. Web Animations API isn't in jsdom, so fall back to an instant leave.
function onLeave(el: Element, done: () => void) {
  const node = el as HTMLElement
  if (typeof node.animate !== 'function') {
    done()
    return
  }
  const height = node.offsetHeight
  node.style.overflow = 'hidden'
  const anim = node.animate(
    [
      { height: `${height}px`, opacity: 1 },
      { height: '0px', opacity: 0 }
    ],
    { duration: 250, easing: 'ease-in-out' }
  )
  anim.onfinish = () => done()
  anim.oncancel = () => done()
}
</script>

<template>
  <!-- One out-in transition spans both states so removing the last event fades
       the list out and the empty state in (mirrors the React skin's mode='wait'
       AnimatePresence). Vue Transitions don't run on initial render, matching
       React's initial={false}. -->
  <Transition
    mode="out-in"
    enter-active-class="transition-opacity duration-200"
    leave-active-class="transition-opacity duration-200"
    enter-from-class="opacity-0"
    leave-to-class="opacity-0"
  >
    <!-- @container + isolate as below; under fillHeight the empty state fills
         and centres in the column. -->
    <div
      v-if="isEmpty"
      key="empty"
      class="@container isolate"
      :class="fillHeight && 'grid min-h-full place-content-center'"
    >
      <CartEmptyState :browse-href="browseHref" :on-navigate="onNavigate" />
    </div>
    <!-- @container so the event-image container queries (@sm/@md in
       CartEventGroup) resolve standalone, exactly as inside the drawer body.
       `isolate` keeps the sticky day headers' z-index contained to the cart —
       without it they paint over app content (the drawer gets this for free
       from its fixed z-modal panel). fillHeight swaps the grid for a fill-height
       flex column. -->
    <div
      v-else
      key="list"
      class="@container isolate"
      :class="fillHeight ? 'flex min-h-full flex-col' : 'grid gap-5'"
    >
      <!-- Once the container is wide (@xl ≈ 576px) the list centres at a readable
         max width and the day headers pick up rounded corners. -->
      <TransitionGroup
        tag="div"
        class="grid gap-5 @xl:mx-auto @xl:w-full @xl:max-w-lg"
        :css="false"
        @leave="onLeave"
      >
        <section
          v-for="group in dayGroups"
          :key="group.key"
          class="-mx-4 grid gap-4 @xl:mx-0"
        >
          <div
            class="sticky top-0 z-sticky emphasis-strong px-4 py-2.5 @xl:rounded-xl"
          >
            <div class="flex items-center gap-2">
              <PhCalendarBlank
                weight="bold"
                class="size-4 shrink-0"
                aria-hidden="true"
              />
              <p class="text-ui-meta font-bold" data-testid="cart-group-title">
                {{ dayHeader(group.key) }}
              </p>
            </div>
          </div>
          <TransitionGroup
            tag="div"
            class="grid gap-4 px-4"
            :css="false"
            @leave="onLeave"
          >
            <div
              v-for="(event, index) in group.events"
              :key="event.eventId"
              class="grid gap-4"
            >
              <div v-if="index > 0" class="pl-6">
                <div
                  role="separator"
                  aria-orientation="horizontal"
                  class="h-px w-full border-t border-solid border-subtle"
                />
              </div>
              <CartEventGroup
                :event="event"
                :locale="locale"
                :currency="currency"
                :busy="busy"
                @remove-event="emit('removeEvent', $event)"
              />
            </div>
          </TransitionGroup>
        </section>
      </TransitionGroup>

      <!-- The footer band stays full-bleed; only its content tracks the same @xl
         max-width column as the list above so they stay aligned. Under
         fillHeight, mt-auto pins it to the bottom for short carts. -->
      <div
        v-if="!hideFooter"
        class="border-t border-subtle pt-4"
        :class="fillHeight && 'mt-auto'"
      >
        <div class="@xl:mx-auto @xl:w-full @xl:max-w-lg">
          <div class="flex items-center justify-between gap-4 pb-1">
            <span class="text-ui font-bold text-strong">Subtotal</span>
            <span class="text-ui font-bold text-strong">
              <NumberFlow
                :value="cart.cartTotal"
                :prefix="pricePrefix"
                :format="PRICE_FORMAT"
              />
            </span>
          </div>
          <p class="pb-4 text-ui-meta text-subtle">
            {{
              totalBookingFees > 0
                ? `Incl. ${money(totalBookingFees)} booking fees. `
                : 'Includes booking fees. '
            }}Delivery and refund protection calculated at checkout.
          </p>
          <!-- Mirrors the drawer footer: neutral secondary + strong-accent
           Checkout with the bag icon. -->
          <div class="flex gap-3">
            <button
              type="button"
              class="is-interactive btn btn-md flex-1 emphasis-normal intent-neutral"
              @click="onNavigate(browseHref)"
            >
              Browse events
            </button>
            <button
              type="button"
              class="is-interactive btn btn-md flex-1 emphasis-strong intent-accent"
              :disabled="!checkoutUrl"
              @click="onCheckout"
            >
              <PhBag
                weight="bold"
                :class="'mr-1.5 size-4'"
                aria-hidden="true"
              />
              Checkout
            </button>
          </div>
        </div>
      </div>
    </div>
  </Transition>
</template>

// packages/widgets/src/cart-contents/react/CartContents.tsx
'use client'

import NumberFlow from '@number-flow/react'
import { BagIcon, CalendarBlankIcon } from '@phosphor-icons/react'
import { AnimatePresence, LazyMotion, domAnimation, m } from 'motion/react'

import { Button, Separator } from '@oztix/roadie-components'
import { cn } from '@oztix/roadie-core/utils'

import {
  type CartDetails,
  currencyPrefix,
  formatCurrency,
  formatDayHeader,
  groupEventsByDay
} from '../../cart'
import { CartEmptyState } from './CartEmptyState'
import { CartEventGroup } from './CartEventGroup'

export type CartContentsProps = {
  cart: CartDetails
  onNavigate: (href: string) => void
  /** App-specific browse target for the empty state. */
  browseHref: string
  /** Pre-validated checkout URL. Null when the safety check failed — CTA disabled. */
  checkoutUrl: string | null
  locale: string
  currency: string
  className?: string
  /** Pin the footer to the bottom of the nearest scrolling ancestor. */
  stickyFooter?: boolean
  /**
   * For standalone `/cart`-style pages: make the root a fill-height column so
   * it fills the height the consumer's container provides. The footer pins to
   * the bottom for short carts (via `mt-auto`) and the empty state centres.
   * Leave unset (the default) inside the drawer, which sizes its own panel.
   */
  fillHeight?: boolean
  /** Skip the Total / fees / Checkout footer. */
  hideFooter?: boolean
  /** Optional per-event remove handler. Receives the `eventId`. */
  onRemoveEvent?: (eventId: string) => void
  /** True while a remove is in flight — disables the trash triggers. */
  busy?: boolean
}

export function CartContents({
  cart,
  onNavigate,
  browseHref,
  checkoutUrl,
  locale,
  currency,
  className,
  stickyFooter = false,
  fillHeight = false,
  hideFooter = false,
  onRemoveEvent,
  busy = false
}: CartContentsProps) {
  const ticketCount = cart.events.reduce(
    (sum, event) =>
      sum + event.tickets.reduce((tSum, t) => tSum + t.quantity, 0),
    0
  )
  const isEmpty = ticketCount === 0

  const dayGroups = groupEventsByDay(cart.events)
  const totalBookingFees = cart.events.reduce(
    (sum, event) => sum + event.bookingFees,
    0
  )

  return (
    // Self-provide motion features so removals animate even when rendered
    // standalone (no drawer LazyMotion ancestor). Nesting inside the drawer's
    // LazyMotion is fine.
    <LazyMotion features={domAnimation}>
      {/* @container so the event-image container queries (@sm/@md in
         CartEventGroup) resolve standalone, exactly as they do inside the
         drawer body's @container. `isolate` keeps the sticky day headers'
         z-index contained to the cart — without it they paint over app
         content (the drawer gets this for free from its fixed z-modal panel).
         fillHeight swaps the default grid for a fill-height flex column. */}
      <div
        className={cn(
          '@container isolate',
          className ?? (fillHeight ? 'flex min-h-full flex-col' : 'grid gap-5')
        )}
      >
        {/* One presence tree spans both states so removing the last event
           animates the list out and the empty state in (mode='wait' →
           sequential crossfade). initial={false} → no animation on first
           mount. */}
        <AnimatePresence mode='wait' initial={false}>
          {isEmpty ? (
            <m.div
              key='empty'
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2 }}
              className={cn(fillHeight && 'grid flex-1 place-content-center')}
            >
              <CartEmptyState browseHref={browseHref} onNavigate={onNavigate} />
            </m.div>
          ) : (
            <m.div
              key='list'
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2 }}
              // Once the container is wide (@xl ≈ 576px) the list stops going
              // edge-to-edge: it centres at a readable max width and the day
              // headers pick up rounded corners (see @xl utilities below).
              className='grid gap-5 @xl:mx-auto @xl:w-full @xl:max-w-lg'
            >
              {/* Per-event removal. exit's overflow is applied only on exit so
                 the sticky header isn't trapped in a scroll container while
                 scrolling. */}
              <AnimatePresence initial={false}>
                {dayGroups.map((group) => (
                  <m.section
                    key={group.key}
                    exit={{ opacity: 0, height: 0, overflow: 'hidden' }}
                    transition={{ duration: 0.25, ease: 'easeInOut' }}
                    // Full-bleed lives on the section (not the header via -mx-4)
                    // so the exit's overflow:hidden clips vertically without
                    // shearing off the header's bleed. At @xl the column is
                    // constrained, so the bleed is dropped and the header rounds.
                    className='-mx-4 grid gap-4 @xl:mx-0'
                  >
                    <div className='sticky top-0 z-sticky emphasis-strong px-4 py-2.5 @xl:rounded-xl'>
                      <div className='flex items-center gap-2'>
                        <CalendarBlankIcon
                          weight='bold'
                          className='size-4 shrink-0'
                        />
                        <p className='text-ui-meta font-bold'>
                          {formatDayHeader(group.key, { locale })}
                        </p>
                      </div>
                    </div>

                    <div className='grid gap-4 px-4'>
                      <AnimatePresence initial={false}>
                        {group.events.map((event, index) => (
                          <m.div
                            key={event.eventId}
                            exit={{ opacity: 0, height: 0, overflow: 'hidden' }}
                            transition={{ duration: 0.25, ease: 'easeInOut' }}
                            className='grid gap-4'
                          >
                            {index > 0 && (
                              <div className='pl-6'>
                                <Separator />
                              </div>
                            )}
                            <CartEventGroup
                              event={event}
                              locale={locale}
                              currency={currency}
                              onRemoveEvent={onRemoveEvent}
                              isRemoving={busy}
                            />
                          </m.div>
                        ))}
                      </AnimatePresence>
                    </div>
                  </m.section>
                ))}
              </AnimatePresence>
            </m.div>
          )}
        </AnimatePresence>

        {!isEmpty && !hideFooter && (
          // The footer band stays full-bleed; only its content tracks the same
          // @xl max-width column as the list above so they stay aligned. Under
          // fillHeight, mt-auto pins it to the bottom for short carts;
          // stickyFooter additionally keeps it pinned while a long cart scrolls.
          <div
            className={cn(
              'border-t border-subtle pt-4',
              fillHeight && 'mt-auto',
              stickyFooter &&
                'sticky bottom-0 bg-raised pb-[env(safe-area-inset-bottom)]'
            )}
          >
            <div className='@xl:mx-auto @xl:w-full @xl:max-w-lg'>
              <div className='flex items-center justify-between gap-4 pb-1'>
                <span className='text-ui font-bold text-strong'>Subtotal</span>
                <NumberFlow
                  value={cart.cartTotal}
                  prefix={currencyPrefix(locale, currency)}
                  format={{ minimumFractionDigits: 2 }}
                  className='text-ui font-bold text-strong'
                />
              </div>
              <p className='pb-4 text-ui-meta text-subtle'>
                {totalBookingFees > 0
                  ? `Incl. ${formatCurrency(totalBookingFees, {
                      locale,
                      currency
                    })} booking fees. `
                  : 'Includes booking fees. '}
                Delivery and refund protection calculated at checkout.
              </p>
              {/* Mirrors the drawer footer: neutral secondary + strong-accent
             Checkout with the bag icon. */}
              <div className='flex gap-3'>
                <Button
                  emphasis='normal'
                  intent='neutral'
                  className='flex-1'
                  onClick={() => onNavigate(browseHref)}
                >
                  Browse events
                </Button>
                <Button
                  emphasis='strong'
                  intent='accent'
                  className='flex-1'
                  disabled={!checkoutUrl}
                  onClick={() => {
                    if (checkoutUrl) onNavigate(checkoutUrl)
                  }}
                >
                  <BagIcon weight='bold' className='mr-1.5 size-4' />
                  Checkout
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>
    </LazyMotion>
  )
}
