// packages/roadie-cart/src/vue/CartEmptyState.vue
<script setup lang="ts">
// Plain button + onNavigate — no router import. Routing is the consumer's job.
const props = defineProps<{
  /** App-specific browse target (replaces the website's hardcoded route). */
  browseHref: string
  onNavigate: (href: string) => void
}>()
</script>

<template>
  <div class="rc-empty">
    <p class="rc-empty__text">Your cart is empty.</p>
    <button
      type="button"
      class="rc-button rc-button--strong rc-intent-brand"
      @click="props.onNavigate(props.browseHref)"
    >
      Browse Events
    </button>
  </div>
</template>

// packages/roadie-cart/src/react/CartEmptyState.tsx
'use client'

import { Button } from '@oztix/roadie-components'

interface CartEmptyStateProps {
  /** App-specific browse target (replaces the website's hardcoded route). */
  browseHref: string
  onNavigate: (href: string) => void
}

export function CartEmptyState({
  browseHref,
  onNavigate
}: CartEmptyStateProps) {
  // Roadie Button + onNavigate — no next/link. Routing is the consumer's job.
  return (
    <div className='grid gap-4'>
      <p className='text-prose text-subtle'>Your cart is empty.</p>
      <Button
        intent='brand'
        emphasis='strong'
        onClick={() => onNavigate(browseHref)}
      >
        Browse Events
      </Button>
    </div>
  )
}
