// packages/widgets/src/cart-drawer/vue/CartDrawer.vue
<script setup lang="ts">
import { PhCircleNotch } from '@phosphor-icons/vue'
import {
  type ComponentPublicInstance,
  computed,
  onBeforeUnmount,
  onMounted,
  ref,
  useId,
  watch,
  watchEffect
} from 'vue'

import {
  BOUNCE_HOLD_MS,
  EMPTY_CLOSE_UNMOUNT_MS,
  type ExpiryWatcher,
  buildBrowseHref,
  createExpiryWatcher,
  deriveBookingFees,
  deriveCartTotal,
  deriveTicketCount,
  isSafeRelativePath
} from '../core'
import CartContents from './CartContents.vue'
import CartDrawerFooter from './CartDrawerFooter.vue'
import CartDrawerHeader from './CartDrawerHeader.vue'
import CartEmptyState from './CartEmptyState.vue'
import { lockBodyScroll } from './documentEffects'
import type { CartDrawerProps } from './types'
import { useCart } from './useCart'
import { useCartDrawerDrag } from './useCartDrawerDrag'

const props = withDefaults(defineProps<CartDrawerProps>(), {
  refreshKey: undefined,
  lockBodyScroll: true,
  initialState: 'closed',
  context: 'collection',
  onOpenChange: undefined,
  onExpire: undefined,
  onHeightChange: undefined
})

const cartHeadingId = useId()

function resolveRootEl(
  el: Element | ComponentPublicInstance | null
): HTMLElement | null {
  if (el instanceof HTMLElement) return el
  const root = (el as ComponentPublicInstance | null)?.$el
  return root instanceof HTMLElement ? root : null
}

// Only accept a consumer browseHref if it's a safe relative path — else a tainted host value could reach onNavigate.
const effectiveBrowseHref = computed(() =>
  typeof props.browseHref === 'string' && isSafeRelativePath(props.browseHref)
    ? props.browseHref
    : buildBrowseHref(props.collectionId)
)

const { summary, details, detailsLoading, detailsError, refresh } = useCart(
  props.cart,
  () => props.collectionId,
  () => props.refreshKey
)

const displayTicketCount = computed(() =>
  deriveTicketCount(details.value, summary.value)
)
const displayTotal = computed(() =>
  deriveCartTotal(details.value, summary.value)
)
const displayBookingFees = computed(() => deriveBookingFees(details.value))

const {
  state,
  toggle,
  dragHeight,
  progress,
  closedHeight,
  isDragging,
  setHeaderElement,
  setFooterElement,
  handleDragStart
} = useCartDrawerDrag({ initialState: props.initialState })

// Stable ref callbacks MUST keep constant identity — an inline arrow re-fires every render → ResizeObserver re-observe loop that freezes the tab.
const bindHeader = (el: Element | ComponentPublicInstance | null): void => {
  setHeaderElement(resolveRootEl(el))
}
const bindFooter = (el: Element | ComponentPublicInstance | null): void => {
  setFooterElement(resolveRootEl(el))
}

const isOpen = computed(() => state.value === 'open')

// High-water latch: once the drawer has shown a cart with items, remember it so
// an empty/null refetch (the API returns null for an emptied cart) keeps the
// open drawer mounted to show the EmptyState instead of vanishing.
const sawCart = ref(false)
const hasCartData = computed(
  () => summary.value != null || details.value != null
)
watchEffect(() => {
  if (hasCartData.value && displayTicketCount.value > 0) sawCart.value = true
})
const isEmpty = computed(
  () =>
    (hasCartData.value && displayTicketCount.value === 0) ||
    (sawCart.value && !hasCartData.value)
)
// Empty + closed → the whole drawer disappears, but only after the close
// slide-down has played (emptyClosed). Empty + open stays mounted so the
// EmptyState shows until the user closes it.
const emptyClosed = ref(false)
let emptyCloseTimer: ReturnType<typeof setTimeout> | null = null
watch(
  () => isEmpty.value && !isOpen.value,
  (closing) => {
    if (emptyCloseTimer !== null) {
      clearTimeout(emptyCloseTimer)
      emptyCloseTimer = null
    }
    if (closing) {
      emptyCloseTimer = setTimeout(() => {
        emptyClosed.value = true
      }, EMPTY_CLOSE_UNMOUNT_MS)
    } else {
      emptyClosed.value = false
    }
  }
)
const hidden = computed(
  () => isEmpty.value && !isOpen.value && emptyClosed.value
)
// Closing an emptied drawer: fade the whole surface out as it slides down so
// the docked bar never reads before it unmounts.
const emptyClosing = computed(() => isEmpty.value && !isOpen.value)

watch(state, (next, prev) => {
  if (next !== prev) props.onOpenChange?.(next === 'open')
})

const bounce = ref(false)
let bounceTimer: ReturnType<typeof setTimeout> | null = null
let prevTicketCount: number | undefined
watch(displayTicketCount, (count) => {
  if (prevTicketCount !== undefined && count > prevTicketCount) {
    bounce.value = true
    if (bounceTimer !== null) clearTimeout(bounceTimer)
    bounceTimer = setTimeout(() => {
      bounce.value = false
    }, BOUNCE_HOLD_MS)
  }
  prevTicketCount = count
})

const expiresAtUtc = computed(
  () => summary.value?.expiresAtUtc ?? details.value?.expiresAtUtc
)
let expireWatcher: ExpiryWatcher | null = null
watch(
  expiresAtUtc,
  (expiry) => {
    expireWatcher?.stop()
    expireWatcher = null
    if (!expiry || !props.onExpire) return
    expireWatcher = createExpiryWatcher(expiry, props.onExpire)
  },
  { immediate: true }
)

watch(
  closedHeight,
  (h) => {
    props.onHeightChange?.(h)
    if (typeof document === 'undefined') return
    document.documentElement.style.setProperty('--cart-drawer-height', `${h}px`)
  },
  { immediate: true }
)

// Body scroll lock when open — refcounted via documentEffects so drawer + expiry modals don't clobber each other's lock.
let releaseScrollLock: (() => void) | null = null
watch(
  [() => props.lockBodyScroll, isOpen],
  ([lock, open]) => {
    if (lock && open) {
      releaseScrollLock ??= lockBodyScroll()
    } else {
      releaseScrollLock?.()
      releaseScrollLock = null
    }
  },
  { immediate: true }
)

function onKeydown(e: KeyboardEvent) {
  if (e.key !== 'Escape' || !isOpen.value) return
  if (document.querySelector('[data-cart-confirm]')) return
  toggle()
}

const drawerEl = ref<HTMLElement | null>(null)
type FocusTrapInstance = { activate: () => void; deactivate: () => void }
let trap: FocusTrapInstance | null = null
async function ensureTrap(): Promise<FocusTrapInstance | null> {
  const el = drawerEl.value
  if (trap || !el) return trap
  try {
    const mod = await import('focus-trap')
    trap = mod.createFocusTrap(el, {
      escapeDeactivates: false,
      clickOutsideDeactivates: true,
      initialFocus: () => drawerEl.value ?? false,
      fallbackFocus: () => drawerEl.value ?? el,
      returnFocusOnDeactivate: true
    })
  } catch {
    trap = null
  }
  return trap
}
watch(isOpen, async (open) => {
  if (open) {
    const t = await ensureTrap()
    if (t && drawerEl.value?.isConnected) {
      try {
        t.activate()
      } catch {
        /* non-fatal */
      }
    }
  } else {
    try {
      trap?.deactivate()
    } catch {
      /* non-fatal */
    }
  }
})

onMounted(() => {
  if (typeof document !== 'undefined') {
    document.addEventListener('keydown', onKeydown)
  }
})
onBeforeUnmount(() => {
  if (bounceTimer !== null) clearTimeout(bounceTimer)
  if (emptyCloseTimer !== null) clearTimeout(emptyCloseTimer)
  expireWatcher?.stop()
  trap?.deactivate()
  releaseScrollLock?.()
  releaseScrollLock = null
  if (typeof document !== 'undefined') {
    document.removeEventListener('keydown', onKeydown)
    document.documentElement.style.removeProperty('--cart-drawer-height')
  }
})

const checkoutUrl = computed(() =>
  details.value ? props.cart.checkoutUrl(details.value) : null
)
function handleCheckout() {
  if (checkoutUrl.value) props.onNavigate(checkoutUrl.value)
}

// Navigates to the validated effectiveBrowseHref only — never a consumer URL — so it can't become an open redirect.
function handleBrowse() {
  props.onNavigate(effectiveBrowseHref.value)
}

const removing = ref(false)
const removeError = ref<string | null>(null)
async function handleRemoveEvent(eventId: string) {
  if (removing.value || !details.value) return
  removing.value = true
  removeError.value = null
  try {
    await props.cart.removeItem(details.value.cartId, eventId)
    await refresh()
  } catch (err) {
    removeError.value =
      err instanceof Error ? err.message : 'Could not remove this event.'
  } finally {
    removing.value = false
  }
}

const overlayOpacity = computed(() => progress.value)
const contentOpacity = computed(() =>
  Math.max(0, Math.min(1, (progress.value - 0.3) / 0.7))
)
</script>

<template>
  <template v-if="collectionId && (summary || details || sawCart) && !hidden">
    <div
      aria-hidden="true"
      class="fixed inset-0 z-overlay emphasis-overlay transition-opacity duration-300 ease-out"
      :class="[
        isOpen ? 'pointer-events-auto' : 'pointer-events-none',
        isDragging && 'transition-none'
      ]"
      :style="{ opacity: overlayOpacity }"
      @click="toggle"
    />

    <div
      ref="drawerEl"
      id="cart-drawer"
      class="fixed z-modal flex flex-col overflow-hidden emphasis-floating [transition:height_320ms_cubic-bezier(0.22,1,0.36,1),border-radius_300ms_var(--ease-out),inset_300ms_var(--ease-out),opacity_300ms_var(--ease-out)] focus:outline-none sm:inset-x-4 sm:bottom-4 sm:mx-auto sm:max-w-[600px] sm:rounded-4xl"
      tabindex="-1"
      :class="[
        isOpen
          ? 'inset-x-0 bottom-0 rounded-t-4xl'
          : 'inset-x-3 bottom-3 rounded-3xl',
        !emptyClosing && 'origin-bottom motion-pop-in',
        isDragging && 'transition-none'
      ]"
      :role="isOpen ? 'dialog' : 'region'"
      :aria-modal="isOpen ? 'true' : undefined"
      :aria-labelledby="isOpen ? cartHeadingId : undefined"
      :aria-label="isOpen ? undefined : 'Cart summary'"
      :style="{ height: `${dragHeight}px`, opacity: emptyClosing ? 0 : 1 }"
    >
      <CartDrawerHeader
        :ref="bindHeader"
        :ticket-count="displayTicketCount"
        :cart-total="displayTotal"
        :expires-at-utc="expiresAtUtc"
        :locale="locale"
        :currency="currency"
        :is-open="isOpen"
        :bounce="bounce"
        :progress="progress"
        :title-id="cartHeadingId"
        @toggle="toggle"
        @drag-start="handleDragStart"
      />

      <div
        id="cart-drawer-body"
        class="h-full min-h-0 flex-1 overflow-y-auto px-4 transition-opacity"
        :aria-busy="removing"
        :inert="!isOpen"
        :style="{
          opacity: contentOpacity,
          pointerEvents: isOpen ? 'auto' : 'none'
        }"
      >
        <p
          v-if="detailsError"
          class="text-prose text-subtle intent-danger"
          role="status"
        >
          Couldn't load your cart. Please try again.
        </p>
        <div
          v-else-if="isEmpty"
          class="grid min-h-full place-content-center"
        >
          <CartEmptyState
            :browse-href="effectiveBrowseHref"
            :on-navigate="onNavigate"
          />
        </div>
        <template v-else-if="details">
          <p
            v-if="removeError"
            class="text-ui-meta text-subtle intent-danger"
            role="alert"
          >
            {{ removeError }}
          </p>
          <div class="relative">
            <div :class="{ 'pointer-events-none opacity-50': removing }">
              <CartContents
                :cart="details"
                :on-navigate="onNavigate"
                :browse-href="effectiveBrowseHref"
                :checkout-url="checkoutUrl"
                :locale="locale"
                :currency="currency"
                :busy="removing"
                hide-footer
                @remove-event="handleRemoveEvent"
              />
            </div>
            <div
              v-if="removing"
              class="pointer-events-none absolute inset-0 grid place-content-center"
              aria-hidden="true"
              data-testid="cart-remove-spinner"
            >
              <PhCircleNotch
                weight="bold"
                :class="'size-6 animate-spin text-subtle'"
                aria-hidden="true"
              />
            </div>
          </div>
        </template>
        <div
          v-else-if="detailsLoading"
          class="grid gap-4"
          data-testid="cart-drawer-loading"
        >
          <div class="h-4 w-40 animate-pulse rounded bg-subtle" />
          <div class="h-32 w-full animate-pulse rounded-xl bg-subtle" />
          <div class="h-32 w-full animate-pulse rounded-xl bg-subtle" />
        </div>
      </div>

      <CartDrawerFooter
        v-if="!isEmpty"
        :ref="bindFooter"
        :cart-total="displayTotal"
        :booking-fees="displayBookingFees"
        :locale="locale"
        :currency="currency"
        :is-open="isOpen"
        :progress="progress"
        :checkout-disabled="!checkoutUrl"
        :context="context"
        @toggle="toggle"
        @checkout="handleCheckout"
        @browse="handleBrowse"
        @drag-start="handleDragStart"
      />
    </div>
  </template>
</template>

// packages/widgets/src/cart-drawer/react/CartDrawer.tsx
'use client'

import {
  type ReactElement,
  useCallback,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState
} from 'react'

import { CircleNotchIcon } from '@phosphor-icons/react'
import { useQueryClient } from '@tanstack/react-query'
import {
  LazyMotion,
  domAnimation,
  m,
  useReducedMotion,
  useTransform
} from 'motion/react'
import FocusLock from 'react-focus-lock'

import { cn } from '@oztix/roadie-core/utils'

import {
  BOUNCE_HOLD_MS,
  type CartClient,
  EMPTY_CLOSE_UNMOUNT_MS,
  buildBrowseHref,
  createExpiryWatcher,
  deriveBookingFees,
  deriveCartTotal,
  deriveTicketCount,
  isSafeRelativePath
} from '../core'
import { CartContents } from './CartContents'
import { CartDrawerFooter, CartDrawerHeader } from './CartDrawerHandle'
import { CartEmptyState } from './CartEmptyState'
import {
  lockBodyScroll as acquireBodyScrollLock,
  clearDrawerHeightVar,
  setDrawerHeightVar
} from './documentEffects'
import { useCartDetails, useCartSummary } from './useCart'
import { useCartBounce } from './useCartBounce'
import { useCartDrawerDrag } from './useCartDrawerDrag'

export type CartDrawerProps = {
  /** Core cart client (host + fetch injected by the consuming app). */
  cart: CartClient
  collectionId: string
  /** REQUIRED — routing is the consumer's job. */
  onNavigate: (href: string) => void
  /** Empty-state "Browse" target. Defaults to a safe collectionId-derived path; unsafe values fall back to that default. */
  browseHref?: string
  /** Mount context for the open-state secondary button. Browse target is package-built from collectionId — never a consumer URL — to avoid open-redirect. */
  context?: 'collection' | 'event'
  /** Locale for currency/date formatting. */
  locale: string
  /** ISO 4217 currency code. */
  currency: string
  /** Bump to force a refetch of summary + details. */
  refreshKey?: number
  /** Lock body scroll while open. Default true. */
  lockBodyScroll?: boolean
  /** Uncontrolled initial state. Default 'closed'. */
  initialState?: 'closed' | 'open'
  /** Fires on open/close transitions. */
  onOpenChange?: (open: boolean) => void
  /** Fires when the urgency countdown hits expiry. */
  onExpire?: () => void
  /** Reports the docked (closed) drawer height in px. */
  onHeightChange?: (px: number) => void
}

export function CartDrawer({
  cart,
  collectionId,
  onNavigate,
  browseHref,
  context = 'collection',
  locale,
  currency,
  refreshKey,
  lockBodyScroll = true,
  initialState = 'closed',
  onOpenChange,
  onExpire,
  onHeightChange
}: CartDrawerProps): ReactElement | null {
  // Reject non-safe-relative browseHref to avoid open-redirect.
  const effectiveBrowseHref = useMemo(
    () =>
      typeof browseHref === 'string' && isSafeRelativePath(browseHref)
        ? browseHref
        : buildBrowseHref(collectionId),
    [browseHref, collectionId]
  )

  const queryClient = useQueryClient()

  const { data: summary } = useCartSummary(cart, collectionId, refreshKey)
  const {
    data: details,
    isLoading: detailsLoading,
    error: detailsError
  } = useCartDetails(cart, collectionId, refreshKey)

  const [removeBusy, setRemoveBusy] = useState(false)
  const [removeError, setRemoveError] = useState<string | null>(null)
  // True once the empty-close slide-down has finished and we can unmount.
  const [emptyClosed, setEmptyClosed] = useState(false)

  const displayTicketCount = useMemo(
    () => deriveTicketCount(details ?? null, summary ?? null),
    [details, summary]
  )
  const displayTotal = useMemo(
    () => deriveCartTotal(details ?? null, summary ?? null),
    [details, summary]
  )
  const displayBookingFees = useMemo(
    () => deriveBookingFees(details ?? null),
    [details]
  )

  const sawCartRef = useRef(false)
  // High-water latch: once the drawer has shown a cart with items, remember it so
  // an empty/null refetch (the API returns null for an emptied cart) keeps the
  // open drawer mounted to show the EmptyState instead of vanishing.
  const hasCartData = summary != null || details != null
  if (hasCartData && displayTicketCount > 0) sawCartRef.current = true
  const isEmpty =
    (hasCartData && displayTicketCount === 0) ||
    (sawCartRef.current && !hasCartData)

  const grabberRef = useRef<HTMLButtonElement | null>(null)
  const cartHeadingId = useId()

  const {
    state,
    toggle,
    dragHeight,
    dragProgress,
    headerHeight,
    footerHeight,
    setHeaderElement,
    setFooterElement,
    handleDragStart,
    isDragging
  } = useCartDrawerDrag({ initialState })

  const prefersReducedMotion = useReducedMotion()

  const prevStateRef = useRef(state)
  useEffect(() => {
    if (prevStateRef.current !== state) {
      prevStateRef.current = state
      onOpenChange?.(state === 'open')
    }
  }, [state, onOpenChange])

  const [bounce, setBounce] = useState(false)
  const bounceTimeoutRef = useRef<number | null>(null)
  const fireBounce = useCallback(() => {
    setBounce(true)
    if (bounceTimeoutRef.current !== null) {
      window.clearTimeout(bounceTimeoutRef.current)
    }
    bounceTimeoutRef.current = window.setTimeout(
      () => setBounce(false),
      BOUNCE_HOLD_MS
    )
  }, [])
  useEffect(() => {
    return () => {
      if (bounceTimeoutRef.current !== null) {
        window.clearTimeout(bounceTimeoutRef.current)
      }
    }
  }, [])
  useCartBounce(displayTicketCount, fireBounce)

  const expiresAtUtc = summary?.expiresAtUtc ?? details?.expiresAtUtc
  useEffect(() => {
    if (!expiresAtUtc || !onExpire) return
    const watcher = createExpiryWatcher(expiresAtUtc, onExpire)
    return () => watcher.stop()
  }, [expiresAtUtc, onExpire])

  const closedHeight = headerHeight + footerHeight
  const heightKeyRef = useRef<object>({})
  useEffect(() => {
    onHeightChange?.(closedHeight)
    const key = heightKeyRef.current
    setDrawerHeightVar(key, closedHeight)
    return () => clearDrawerHeightVar(key)
  }, [closedHeight, onHeightChange])

  useEffect(() => {
    if (!lockBodyScroll || state !== 'open') return
    return acquireBodyScrollLock()
  }, [lockBodyScroll, state])

  // Defer the unmount of an emptied, closed drawer until the close slide-down
  // has played, so it animates out the same way a normal close does.
  useEffect(() => {
    if (isEmpty && state === 'closed') {
      const t = window.setTimeout(
        () => setEmptyClosed(true),
        EMPTY_CLOSE_UNMOUNT_MS
      )
      return () => window.clearTimeout(t)
    }
    setEmptyClosed(false)
  }, [isEmpty, state])

  useEffect(() => {
    if (state !== 'open') return
    const onKey = (e: KeyboardEvent) => {
      if (e.key !== 'Escape') return
      if (document.querySelector('[data-slot="popover-popup"]')) return
      toggle()
    }
    document.addEventListener('keydown', onKey)
    return () => document.removeEventListener('keydown', onKey)
  }, [state, toggle])

  const overlayOpacity = useTransform(dragProgress, [0, 1], [0, 1])
  const contentOpacity = useTransform(dragProgress, [0.3, 1], [0, 1])

  const checkoutUrl = details ? cart.checkoutUrl(details) : null
  const handleCheckout = useCallback(() => {
    if (checkoutUrl) onNavigate(checkoutUrl)
  }, [checkoutUrl, onNavigate])

  const handleBrowse = useCallback(() => {
    onNavigate(effectiveBrowseHref)
  }, [effectiveBrowseHref, onNavigate])

  const removeEvent = useCallback(
    async (eventId: string) => {
      if (!details || removeBusy) return
      setRemoveBusy(true)
      setRemoveError(null)
      try {
        await cart.removeItem(details.cartId, eventId)
        await Promise.all([
          queryClient.invalidateQueries({
            queryKey: ['roadieCartDetails', collectionId]
          }),
          queryClient.invalidateQueries({
            queryKey: ['roadieCartSummary', collectionId]
          })
        ])
      } catch (err) {
        setRemoveError(
          err instanceof Error ? err.message : 'Could not remove this event.'
        )
      } finally {
        setRemoveBusy(false)
      }
    },
    [cart, details, collectionId, queryClient, removeBusy]
  )

  if (!collectionId) return null
  // Never had a cart → render nothing. Once we've shown one (sawCartRef), an
  // emptied/null refetch keeps us mounted so the EmptyState can show.
  if (!summary && !details && !sawCartRef.current) return null
  // Empty + closed → the whole drawer disappears (no docked handle), but only
  // after the close slide-down has played (emptyClosed). Empty + open stays
  // mounted so the EmptyState shows until the user closes it.
  if (isEmpty && state === 'closed' && emptyClosed) return null

  // Closing an emptied drawer: fade the whole surface out as it slides down so
  // the docked bar never reads before it unmounts.
  const emptyClosing = isEmpty && state === 'closed'

  return (
    <LazyMotion features={domAnimation} strict>
      <m.div
        aria-hidden='true'
        onClick={toggle}
        className={cn(
          'fixed inset-0 z-overlay emphasis-overlay transition-opacity duration-300 ease-out',
          state === 'open' ? 'pointer-events-auto' : 'pointer-events-none',
          isDragging && 'transition-none'
        )}
        style={{ opacity: overlayOpacity }}
      />

      <m.div
        id='cart-drawer'
        {...(state === 'open'
          ? {
              role: 'dialog',
              'aria-modal': true,
              'aria-labelledby': cartHeadingId
            }
          : {
              role: 'region',
              'aria-label': 'Cart summary'
            })}
        initial={
          prefersReducedMotion ? false : { opacity: 0, scale: 0.96, y: 8 }
        }
        animate={{ opacity: emptyClosing ? 0 : 1, scale: 1, y: 0 }}
        transition={{ duration: 0.35, ease: 'easeOut' }}
        className={cn(
          'fixed z-modal flex flex-col overflow-hidden emphasis-floating',
          'transition-[border-radius,inset] duration-300 ease-out',
          state === 'open'
            ? 'inset-x-0 bottom-0 rounded-t-4xl'
            : 'inset-x-3 bottom-3 rounded-3xl',
          'sm:inset-x-4 sm:bottom-4 sm:mx-auto sm:max-w-[600px] sm:rounded-4xl',
          isDragging && 'transition-none'
        )}
        style={{ height: dragHeight, transformOrigin: 'bottom' }}
      >
        <FocusLock
          returnFocus
          disabled={state !== 'open'}
          className='flex h-full min-h-0 flex-col'
        >
          <CartDrawerHeader
            ticketCount={displayTicketCount}
            cartTotal={displayTotal}
            expiresAtUtc={expiresAtUtc}
            locale={locale}
            currency={currency}
            isOpen={state === 'open'}
            bounce={bounce}
            progress={dragProgress}
            onToggle={toggle}
            onPointerDown={handleDragStart}
            headerRef={setHeaderElement}
            grabberRef={grabberRef}
            titleId={cartHeadingId}
          />

          <m.div
            className='relative min-h-0 flex-1'
            style={{
              opacity: contentOpacity,
              pointerEvents: state === 'open' ? 'auto' : 'none'
            }}
          >
            <div
              id='cart-drawer-body'
              aria-busy={removeBusy}
              inert={state !== 'open'}
              className={cn(
                'h-full overflow-y-auto px-4 transition-opacity',
                removeBusy && 'pointer-events-none opacity-50'
              )}
            >
              {removeError && (
                <p
                  role='alert'
                  className='text-ui-meta text-subtle intent-danger'
                >
                  {removeError}
                </p>
              )}
              {detailsError ? (
                <p
                  className='text-prose text-subtle intent-danger'
                  role='status'
                >
                  Couldn&apos;t load your cart. Please try again.
                </p>
              ) : isEmpty ? (
                <CartEmptyState
                  browseHref={effectiveBrowseHref}
                  onNavigate={onNavigate}
                />
              ) : details ? (
                <CartContents
                  cart={details}
                  onNavigate={onNavigate}
                  browseHref={effectiveBrowseHref}
                  checkoutUrl={checkoutUrl}
                  locale={locale}
                  currency={currency}
                  hideFooter
                  onRemoveEvent={removeEvent}
                  busy={removeBusy}
                />
              ) : detailsLoading ? (
                <div className='grid gap-4' data-testid='cart-drawer-loading'>
                  <div className='h-4 w-40 animate-pulse rounded bg-subtle' />
                  <div className='h-32 w-full animate-pulse rounded-xl bg-subtle' />
                  <div className='h-32 w-full animate-pulse rounded-xl bg-subtle' />
                </div>
              ) : null}
            </div>

            {removeBusy && (
              <div
                aria-hidden='true'
                className='pointer-events-none absolute inset-0 grid place-content-center'
              >
                <CircleNotchIcon
                  weight='bold'
                  className='size-6 animate-spin text-subtle'
                />
              </div>
            )}
          </m.div>

          {!isEmpty && (
            <CartDrawerFooter
              cartTotal={displayTotal}
              bookingFees={displayBookingFees}
              locale={locale}
              currency={currency}
              isOpen={state === 'open'}
              progress={dragProgress}
              context={context}
              onToggle={toggle}
              onCheckout={handleCheckout}
              onBrowse={handleBrowse}
              checkoutDisabled={!checkoutUrl}
              onPointerDown={handleDragStart}
              footerRef={setFooterElement}
            />
          )}
        </FocusLock>
      </m.div>
    </LazyMotion>
  )
}
