// packages/roadie-cart/src/vue/CartContents.vue
<script setup lang="ts">
import { computed } from 'vue'

import {
  type CartDetails,
  formatCurrency,
  formatDayHeader,
  groupEventsByDay
} from '../core'
import CartEmptyState from './CartEmptyState.vue'
import CartEventGroup from './CartEventGroup.vue'

const props = withDefaults(
  defineProps<{
    cart: CartDetails
    onNavigate: (href: string) => void
    /** App-specific browse target for the empty state (design finding #4). */
    browseHref: string
    /** Pre-validated checkout URL; null disables the CTA (unsafe extrasUrl). */
    checkoutUrl: string | null
    locale: string
    currency: string
    /** Skip the Total / fees / Checkout footer (the drawer renders its own). */
    hideFooter?: boolean
  }>(),
  { hideFooter: false }
)

const ticketCount = computed(() =>
  props.cart.events.reduce(
    (sum, event) =>
      sum + event.tickets.reduce((tSum, t) => tSum + t.quantity, 0),
    0
  )
)
const isEmpty = computed(() => ticketCount.value === 0)

// Core groups by venue-local eventDateKey and orders by eventStartAtUtc.
const dayGroups = computed(() => groupEventsByDay(props.cart.events))
const totalBookingFees = computed(() =>
  props.cart.events.reduce((sum, event) => sum + event.bookingFees, 0)
)

function dayHeader(key: string): string {
  return formatDayHeader(key, { locale: props.locale })
}
function money(amount: number): string {
  return formatCurrency(amount, {
    locale: props.locale,
    currency: props.currency
  })
}
function onCheckout() {
  if (props.checkoutUrl) props.onNavigate(props.checkoutUrl)
}
</script>

<template>
  <CartEmptyState
    v-if="isEmpty"
    :browse-href="browseHref"
    :on-navigate="onNavigate"
  />
  <div v-else class="rc-contents">
    <div class="rc-contents__groups">
      <section v-for="group in dayGroups" :key="group.key" class="rc-group">
        <div class="rc-group__header">
          <svg viewBox="0 0 256 256" fill="currentColor" aria-hidden="true">
            <path
              d="M208,32H184V24a8,8,0,0,0-16,0v8H88V24a8,8,0,0,0-16,0v8H48A16,16,0,0,0,32,48V208a16,16,0,0,0,16,16H208a16,16,0,0,0,16-16V48A16,16,0,0,0,208,32Zm0,176H48V96H208V208Zm0-128H48V48H208Z"
            />
          </svg>
          <p class="rc-group__title">{{ dayHeader(group.key) }}</p>
        </div>
        <div class="rc-group__events">
          <CartEventGroup
            v-for="event in group.events"
            :key="event.eventId"
            :event="event"
            :locale="locale"
            :currency="currency"
          />
        </div>
      </section>
    </div>

    <div v-if="!hideFooter" class="rc-contents__footer">
      <div class="rc-contents__total">
        <span class="rc-contents__total-label">Total</span>
        <span class="rc-contents__total-value">{{
          money(cart.cartTotal)
        }}</span>
      </div>
      <p class="rc-contents__fees">
        {{
          totalBookingFees > 0
            ? `Incl. ${money(totalBookingFees)} booking fees. `
            : 'Includes booking fees. '
        }}Delivery and refund protection calculated at checkout
      </p>
      <button
        type="button"
        class="rc-button rc-button--normal rc-intent-brand"
        :disabled="!checkoutUrl"
        @click="onCheckout"
      >
        Checkout
      </button>
    </div>
  </div>
</template>

// packages/widgets/src/cart-drawer/react/CartContents.tsx
'use client'

import { Button } from '@oztix/roadie-components'
import { cn } from '@oztix/roadie-core/utils'

import {
  type CartDetails,
  formatCurrency,
  formatDayHeader,
  groupEventsByDay
} from '../core'
import { CartEmptyState } from './CartEmptyState'
import { CartEventGroup } from './CartEventGroup'
import { CalendarBlankIcon } from './icons'

interface CartContentsProps {
  cart: CartDetails
  onNavigate: (href: string) => void
  /** App-specific browse target for the empty state (design finding #4). */
  browseHref: string
  /** Pre-validated checkout URL from `cart.checkoutUrl(details)`. Null when the
   * extrasUrl failed the same-origin safety check — the CTA is then disabled. */
  checkoutUrl: string | null
  locale: string
  currency: string
  className?: string
  /** Pin the footer to the bottom of the nearest scrolling ancestor. */
  stickyFooter?: boolean
  /** Skip the Total / fees / Checkout footer (the drawer renders its own). */
  hideFooter?: boolean
}

export function CartContents({
  cart,
  onNavigate,
  browseHref,
  checkoutUrl,
  locale,
  currency,
  className,
  stickyFooter = false,
  hideFooter = false
}: CartContentsProps) {
  const ticketCount = cart.events.reduce(
    (sum, event) =>
      sum + event.tickets.reduce((tSum, t) => tSum + t.quantity, 0),
    0
  )
  if (ticketCount === 0) {
    return <CartEmptyState browseHref={browseHref} onNavigate={onNavigate} />
  }

  // Core groups by venue-local eventDateKey and orders by eventStartAtUtc.
  const dayGroups = groupEventsByDay(cart.events)
  const totalBookingFees = cart.events.reduce(
    (sum, event) => sum + event.bookingFees,
    0
  )

  return (
    <div className={className ?? 'grid gap-6'}>
      <div className='grid gap-5'>
        {dayGroups.map((group) => (
          <section key={group.key} className='grid gap-3'>
            <div className='sticky top-0 z-10 -mx-4 emphasis-strong px-4 py-2.5'>
              <div className='flex items-center gap-2'>
                <CalendarBlankIcon className='size-4 shrink-0 text-subtle' />
                <p className='text-ui-meta font-bold'>
                  {formatDayHeader(group.key, { locale })}
                </p>
              </div>
            </div>

            <div className='grid gap-4'>
              {group.events.map((event) => (
                <CartEventGroup
                  key={event.eventId}
                  event={event}
                  locale={locale}
                  currency={currency}
                />
              ))}
            </div>
          </section>
        ))}
      </div>

      {!hideFooter && (
        <div
          className={cn(
            'grid gap-4 border-t border-subtle pt-4',
            stickyFooter &&
              'sticky bottom-0 bg-raised pb-[env(safe-area-inset-bottom)]'
          )}
        >
          <div className='flex items-center justify-between gap-4'>
            <span className='text-ui font-bold text-strong'>Total</span>
            <span className='text-ui font-bold text-strong'>
              {formatCurrency(cart.cartTotal, { locale, currency })}
            </span>
          </div>
          <p className='text-ui-meta text-subtle'>
            {totalBookingFees > 0
              ? `Incl. ${formatCurrency(totalBookingFees, {
                  locale,
                  currency
                })} booking fees. `
              : 'Includes booking fees. '}
            Delivery and refund protection calculated at checkout
          </p>
          <Button
            emphasis='normal'
            intent='brand'
            disabled={!checkoutUrl}
            onClick={() => {
              if (checkoutUrl) onNavigate(checkoutUrl)
            }}
          >
            Checkout
          </Button>
        </div>
      )}
    </div>
  )
}
