// packages/widgets/src/cart-drawer/react/CartEmptyState.tsx
'use client'

import { BagIcon } from '@phosphor-icons/react'

import { Button } from '@oztix/roadie-components'

type CartEmptyStateProps = {
  /** App-specific browse target (replaces the website's hardcoded route). */
  browseHref: string
  onNavigate: (href: string) => void
}

export function CartEmptyState({
  browseHref,
  onNavigate
}: CartEmptyStateProps) {
  // Centered empty state (parity with the Website). Roadie Button + onNavigate
  // — no next/link; routing is the consumer's job.
  return (
    <div className='flex flex-col items-center justify-center px-6 py-16 text-center'>
      <div className='mb-6 flex size-24 items-center justify-center rounded-full bg-subtle'>
        <BagIcon
          weight='bold'
          className='size-10 text-subtler'
          aria-hidden='true'
        />
      </div>
      <h2 className='mb-2 text-display-ui-3 text-strong'>Your cart is empty</h2>
      <p className='mb-6 max-w-xs text-prose text-balance text-subtle'>
        Browse events and add tickets to get started.
      </p>
      <Button
        intent='brand'
        emphasis='strong'
        size='lg'
        onClick={() => onNavigate(browseHref)}
      >
        Browse Events
      </Button>
    </div>
  )
}

// packages/widgets/src/cart-contents/vue/CartEmptyState.vue
<script setup lang="ts">
import { PhBag } from '@phosphor-icons/vue'

const props = defineProps<{
  /** App-specific browse target. */
  browseHref: string
  onNavigate: (href: string) => void
}>()
</script>

<template>
  <!-- Hand-port of the Roadie EmptyState compound (size sm) — class strings
       copied from packages/components/src/components/EmptyState. -->
  <div
    data-slot="empty-state"
    class="grid justify-items-center gap-4 py-8 text-center"
  >
    <div
      data-slot="empty-state-icon-tile"
      class="inline-flex size-14 items-center justify-center rounded-full emphasis-subtle p-3 text-subtle [&_svg]:size-8 [&_svg]:shrink-0"
    >
      <PhBag weight="duotone" aria-hidden="true" />
    </div>
    <h2
      data-slot="empty-state-title"
      class="text-display-ui-5 text-balance text-strong"
    >
      Your cart is empty
    </h2>
    <p
      data-slot="empty-state-description"
      class="max-w-sm text-sm/prose tracking-prose text-pretty text-subtle [[data-slot=empty-state-title]+&]:-mt-3"
    >
      Browse events and add tickets to get started.
    </p>
    <div class="flex flex-wrap items-center justify-center gap-3">
      <button
        type="button"
        class="is-interactive btn btn-md emphasis-strong intent-brand"
        @click="props.onNavigate(props.browseHref)"
      >
        Browse events
      </button>
    </div>
  </div>
</template>
