// packages/widgets/src/cart-drawer/react/CartContents.tsx
'use client'

import { CalendarBlankIcon } from '@phosphor-icons/react'

import { Button } from '@oztix/roadie-components'
import { cn } from '@oztix/roadie-core/utils'

import {
  type CartDetails,
  formatCurrency,
  formatDayHeader,
  groupEventsByDay
} from '../core'
import { CartEmptyState } from './CartEmptyState'
import { CartEventGroup } from './CartEventGroup'

type CartContentsProps = {
  cart: CartDetails
  onNavigate: (href: string) => void
  /** App-specific browse target for the empty state. */
  browseHref: string
  /** Pre-validated checkout URL. Null when the safety check failed — CTA disabled. */
  checkoutUrl: string | null
  locale: string
  currency: string
  className?: string
  /** Pin the footer to the bottom of the nearest scrolling ancestor. */
  stickyFooter?: boolean
  /** Skip the Total / fees / Checkout footer. */
  hideFooter?: boolean
  /** Optional per-event remove handler. Receives the `eventId`. */
  onRemoveEvent?: (eventId: string) => void
  /** True while a remove is in flight — disables the trash triggers. */
  busy?: boolean
}

export function CartContents({
  cart,
  onNavigate,
  browseHref,
  checkoutUrl,
  locale,
  currency,
  className,
  stickyFooter = false,
  hideFooter = false,
  onRemoveEvent,
  busy = false
}: CartContentsProps) {
  const ticketCount = cart.events.reduce(
    (sum, event) =>
      sum + event.tickets.reduce((tSum, t) => tSum + t.quantity, 0),
    0
  )
  if (ticketCount === 0) {
    return <CartEmptyState browseHref={browseHref} onNavigate={onNavigate} />
  }

  const dayGroups = groupEventsByDay(cart.events)
  const totalBookingFees = cart.events.reduce(
    (sum, event) => sum + event.bookingFees,
    0
  )

  return (
    <div className={className ?? 'grid gap-5'}>
      {dayGroups.map((group) => (
        <section key={group.key} className='grid gap-4'>
          <div className='sticky top-0 z-10 -mx-4 emphasis-strong px-4 py-2.5'>
            <div className='flex items-center gap-2'>
              <CalendarBlankIcon
                weight='bold'
                className='size-4 shrink-0 text-subtle'
              />
              <p className='text-ui-meta font-bold'>
                {formatDayHeader(group.key, { locale })}
              </p>
            </div>
          </div>

          <div className='grid gap-4'>
            {group.events.map((event) => (
              <CartEventGroup
                key={event.eventId}
                event={event}
                locale={locale}
                currency={currency}
                onRemoveEvent={onRemoveEvent}
                isRemoving={busy}
              />
            ))}
          </div>
        </section>
      ))}

      {!hideFooter && (
        <div
          className={cn(
            'grid gap-4 border-t border-subtle pt-4',
            stickyFooter &&
              'sticky bottom-0 bg-raised pb-[env(safe-area-inset-bottom)]'
          )}
        >
          <div className='flex items-center justify-between gap-4'>
            <span className='text-ui font-bold text-strong'>Total</span>
            <span className='text-ui font-bold text-strong'>
              {formatCurrency(cart.cartTotal, { locale, currency })}
            </span>
          </div>
          <p className='text-ui-meta text-subtle'>
            {totalBookingFees > 0
              ? `Incl. ${formatCurrency(totalBookingFees, {
                  locale,
                  currency
                })} booking fees. `
              : 'Includes booking fees. '}
            Delivery and refund protection calculated at checkout
          </p>
          <Button
            emphasis='normal'
            intent='brand'
            disabled={!checkoutUrl}
            onClick={() => {
              if (checkoutUrl) onNavigate(checkoutUrl)
            }}
          >
            Checkout
          </Button>
        </div>
      )}
    </div>
  )
}

// packages/widgets/src/cart-drawer/vue/CartContents.vue
<script setup lang="ts">
import { PhCalendarBlank } from '@phosphor-icons/vue'
import { computed } from 'vue'

import {
  type CartDetails,
  formatCurrency,
  formatDayHeader,
  groupEventsByDay
} from '../core'
import CartEmptyState from './CartEmptyState.vue'
import CartEventGroup from './CartEventGroup.vue'

const props = withDefaults(
  defineProps<{
    cart: CartDetails
    onNavigate: (href: string) => void
    /** App-specific browse target for the empty state (design finding #4). */
    browseHref: string
    /** Pre-validated checkout URL; null disables the CTA (unsafe extrasUrl). */
    checkoutUrl: string | null
    locale: string
    currency: string
    /** Skip the Total / fees / Checkout footer (the drawer renders its own). */
    hideFooter?: boolean
    /** True while a cart-wide remove is in flight — locks the per-event trash. */
    busy?: boolean
  }>(),
  { hideFooter: false }
)

const emit = defineEmits<{
  removeEvent: [eventId: string]
}>()

const ticketCount = computed(() =>
  props.cart.events.reduce(
    (sum, event) =>
      sum + event.tickets.reduce((tSum, t) => tSum + t.quantity, 0),
    0
  )
)
const isEmpty = computed(() => ticketCount.value === 0)

const dayGroups = computed(() => groupEventsByDay(props.cart.events))
const totalBookingFees = computed(() =>
  props.cart.events.reduce((sum, event) => sum + event.bookingFees, 0)
)

function dayHeader(key: string): string {
  return formatDayHeader(key, { locale: props.locale })
}
function money(amount: number): string {
  return formatCurrency(amount, {
    locale: props.locale,
    currency: props.currency
  })
}
function onCheckout() {
  if (props.checkoutUrl) props.onNavigate(props.checkoutUrl)
}
</script>

<template>
  <CartEmptyState
    v-if="isEmpty"
    :browse-href="browseHref"
    :on-navigate="onNavigate"
  />
  <div v-else class="grid gap-5">
    <section v-for="group in dayGroups" :key="group.key" class="grid gap-4">
      <div class="sticky top-0 z-10 -mx-4 emphasis-strong px-4 py-2.5">
        <div class="flex items-center gap-2">
          <PhCalendarBlank
            weight="bold"
            class="size-4 shrink-0 text-subtle"
            aria-hidden="true"
          />
          <p class="text-ui-meta font-bold" data-testid="cart-group-title">
            {{ dayHeader(group.key) }}
          </p>
        </div>
      </div>
      <div class="grid gap-4">
        <CartEventGroup
          v-for="event in group.events"
          :key="event.eventId"
          :event="event"
          :locale="locale"
          :currency="currency"
          :busy="busy"
          @remove-event="emit('removeEvent', $event)"
        />
      </div>
    </section>

    <div v-if="!hideFooter" class="grid gap-4 border-t border-subtle pt-4">
      <div class="flex items-center justify-between gap-4">
        <span class="text-ui font-bold text-strong">Total</span>
        <span class="text-ui font-bold text-strong">{{
          money(cart.cartTotal)
        }}</span>
      </div>
      <p class="text-ui-meta text-subtle">
        {{
          totalBookingFees > 0
            ? `Incl. ${money(totalBookingFees)} booking fees. `
            : 'Includes booking fees. '
        }}Delivery and refund protection calculated at checkout
      </p>
      <button
        type="button"
        class="is-interactive btn btn-md emphasis-normal intent-brand"
        :disabled="!checkoutUrl"
        @click="onCheckout"
      >
        Checkout
      </button>
    </div>
  </div>
</template>
