// packages/widgets/src/cart-drawer/react/CartEventGroup.tsx
'use client'

import { useState } from 'react'

import { ClockIcon, MapPinIcon, TrashIcon } from '@phosphor-icons/react'

import { Button, IconButton, Popover } from '@oztix/roadie-components'

import {
  type CartEvent,
  formatCurrency,
  formatTime,
  isSafeImageUrl
} from '../core'

type CartEventGroupProps = {
  event: CartEvent
  /** Locale for currency/time formatting (design finding #1). */
  locale: string
  /** ISO 4217 currency code (design finding #1). */
  currency: string
  /**
   * Optional remove handler. When supplied, a per-event trash button +
   * confirmation popover render in the header. Receives the `eventId`; the
   * owner (CartDrawer) runs the actual `cart.removeItem` + refetch flow. Kept
   * presentational — this component never calls the client itself.
   */
  onRemoveEvent?: (eventId: string) => void
  /** True while a remove is in flight — disables the trash trigger. */
  isRemoving?: boolean
}

export function CartEventGroup({
  event,
  locale,
  currency,
  onRemoveEvent,
  isRemoving = false
}: CartEventGroupProps) {
  // Controlled so "Remove" can fire the callback and close in one click.
  const [confirmOpen, setConfirmOpen] = useState(false)
  // Time of day comes from the UTC start; eventDateDisplay (if provided) is the
  // pre-formatted venue-local string, otherwise we render the wall-clock time.
  const start = new Date(event.eventStartAtUtc)
  const startValid = !Number.isNaN(start.getTime())
  const timeLabel =
    event.eventDateDisplay ?? (startValid ? formatTime(start) : null)
  // Only render API-supplied images from absolute http(s) URLs — a hostile API
  // could otherwise beacon viewers via a protocol-relative tracking pixel.
  const safeImageUrl = isSafeImageUrl(event.imageUrl) ? event.imageUrl : null

  return (
    <div className='grid gap-3'>
      <div className='flex items-start gap-3'>
        <div className='flex min-w-0 flex-1 flex-col gap-1'>
          {timeLabel && (
            <div className='flex items-center gap-2 text-ui-meta text-subtle'>
              <ClockIcon
                weight='bold'
                className='size-4 shrink-0 text-subtler'
              />
              <span>{timeLabel}</span>
            </div>
          )}
          <div className='grid gap-1 pl-6'>
            <p className='text-ui font-medium text-strong'>{event.eventName}</p>
            <div className='flex items-center gap-1.5 text-ui-meta text-subtle'>
              <MapPinIcon
                weight='bold'
                className='size-3.5 shrink-0 text-subtler'
              />
              <span>{event.venueName}</span>
            </div>
          </div>
        </div>
        {safeImageUrl && (
          <img
            src={safeImageUrl}
            alt={event.eventName}
            className='size-20 shrink-0 rounded-lg bg-subtle object-cover'
          />
        )}
        {onRemoveEvent && (
          <Popover open={confirmOpen} onOpenChange={setConfirmOpen}>
            <Popover.Trigger
              render={
                <IconButton
                  intent='danger'
                  emphasis='subtler'
                  size='sm'
                  disabled={isRemoving}
                  aria-label={`Remove ${event.eventName}`}
                >
                  <TrashIcon weight='bold' className='size-4' />
                </IconButton>
              }
            />
            <Popover.Content intent='danger'>
              <Popover.Body>
                <p className='text-ui text-pretty text-strong'>
                  Remove all tickets for this event?
                </p>
              </Popover.Body>
              <Popover.Footer>
                <Popover.Close
                  render={
                    <Button intent='neutral' emphasis='normal' size='sm'>
                      Cancel
                    </Button>
                  }
                />
                <Button
                  intent='danger'
                  emphasis='strong'
                  size='sm'
                  onClick={() => {
                    onRemoveEvent(event.eventId)
                    setConfirmOpen(false)
                  }}
                >
                  Remove
                </Button>
              </Popover.Footer>
            </Popover.Content>
          </Popover>
        )}
      </div>

      <div className='grid gap-3 pl-6'>
        {event.tickets.map((ticket) => (
          <div key={ticket.name} className='grid gap-2'>
            <div className='md:hidden'>
              <p className='text-ui font-medium text-strong'>{ticket.name}</p>
            </div>
            <div className='flex items-center rounded-lg bg-sunken px-3 py-2'>
              <div className='hidden min-w-0 flex-1 pr-4 md:block'>
                <span className='block truncate text-ui font-medium text-strong'>
                  {ticket.name}
                </span>
              </div>
              <span className='w-20 shrink-0 text-ui-meta text-subtle'>
                {ticket.priceEach === 0
                  ? 'Free'
                  : formatCurrency(ticket.priceEach, { locale, currency })}
              </span>
              <div className='flex flex-1 items-center justify-center'>
                <span className='shrink-0 text-ui-meta font-medium text-strong'>
                  &times; {ticket.quantity}
                </span>
              </div>
              <span className='w-24 shrink-0 text-right text-ui font-bold text-strong tabular-nums'>
                {formatCurrency(ticket.quantity * ticket.priceEach, {
                  locale,
                  currency
                })}
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

// packages/widgets/src/cart-drawer/vue/CartEventGroup.vue
<script setup lang="ts">
import { PhClock, PhMapPin, PhTrash } from '@phosphor-icons/vue'
import { computed, onBeforeUnmount, ref, watch } from 'vue'

import {
  type CartEvent,
  formatCurrency,
  formatTime,
  isSafeImageUrl
} from '../core'

const props = defineProps<{
  event: CartEvent
  /** Locale for currency/time formatting (design finding #1). */
  locale: string
  /** ISO 4217 currency code (design finding #1). */
  currency: string
  /** True while a cart-wide remove is in flight — disables the trash/confirm. */
  busy?: boolean
}>()

// Presentational only: bubble the eventId up. The parent (CartDrawer) owns the
// remove flow (lock cart → cart.removeItem → refresh) — this component never
// touches the cart client itself.
const emit = defineEmits<{
  removeEvent: [eventId: string]
}>()

// Time of day from the UTC start; eventDateDisplay (if provided) wins.
const timeLabel = computed(() => {
  const start = new Date(props.event.eventStartAtUtc)
  const valid = !Number.isNaN(start.getTime())
  return props.event.eventDateDisplay ?? (valid ? formatTime(start) : null)
})

// Only render API-supplied images from absolute http(s) URLs — a hostile API
// could otherwise beacon viewers via a protocol-relative tracking pixel.
const safeImageUrl = computed(() =>
  isSafeImageUrl(props.event.imageUrl) ? props.event.imageUrl : null
)

function money(amount: number): string {
  return formatCurrency(amount, {
    locale: props.locale,
    currency: props.currency
  })
}

// --- Confirm popover (hand-rolled: absolutely-positioned card + click-outside,
// the same approach the prototype uses; no Base UI / Tailwind in this skin). ---
const confirming = ref(false)
const removeWrapEl = ref<HTMLElement | null>(null)
// Stable ids so the trigger's aria-controls and the dialog's accessible name
// (aria-labelledby -> the prompt) resolve per-event.
const confirmId = computed(() => `cart-confirm-${props.event.eventId}`)
const confirmLabelId = computed(
  () => `cart-confirm-label-${props.event.eventId}`
)

function openConfirm() {
  if (props.busy) return
  confirming.value = true
}
function closeConfirm() {
  confirming.value = false
}
function confirmRemove() {
  emit('removeEvent', props.event.eventId)
  confirming.value = false
}

// Dismiss on outside pointerdown (mousedown parity with the prototype) and on
// Escape. Listeners attach only while open so a closed popover costs nothing.
function onDocumentPointerDown(e: MouseEvent) {
  if (removeWrapEl.value && !removeWrapEl.value.contains(e.target as Node)) {
    closeConfirm()
  }
}
function onDocumentKeydown(e: KeyboardEvent) {
  if (e.key === 'Escape') closeConfirm()
}
watch(confirming, (open) => {
  if (typeof document === 'undefined') return
  if (open) {
    document.addEventListener('mousedown', onDocumentPointerDown)
    document.addEventListener('keydown', onDocumentKeydown)
  } else {
    document.removeEventListener('mousedown', onDocumentPointerDown)
    document.removeEventListener('keydown', onDocumentKeydown)
  }
})
onBeforeUnmount(() => {
  if (typeof document === 'undefined') return
  document.removeEventListener('mousedown', onDocumentPointerDown)
  document.removeEventListener('keydown', onDocumentKeydown)
})
</script>

<template>
  <div class="grid gap-3">
    <div class="flex items-start gap-3">
      <div class="flex min-w-0 flex-1 flex-col gap-1">
        <div
          v-if="timeLabel"
          class="flex items-center gap-2 text-ui-meta text-subtle"
        >
          <PhClock
            weight="bold"
            class="size-4 shrink-0 text-subtler"
            aria-hidden="true"
          />
          <span>{{ timeLabel }}</span>
        </div>
        <div class="grid gap-1 pl-6">
          <p class="text-ui font-medium text-strong">{{ event.eventName }}</p>
          <div class="flex items-center gap-1.5 text-ui-meta text-subtle">
            <PhMapPin
              weight="bold"
              class="size-3.5 shrink-0 text-subtler"
              aria-hidden="true"
            />
            <span>{{ event.venueName }}</span>
          </div>
        </div>
      </div>
      <img
        v-if="safeImageUrl"
        :src="safeImageUrl"
        :alt="event.eventName"
        class="size-20 shrink-0 rounded-lg bg-subtle object-cover"
      />
      <div ref="removeWrapEl" class="relative shrink-0 self-start">
        <button
          type="button"
          class="btn-icon is-interactive btn-icon-sm emphasis-subtler intent-danger"
          :aria-label="`Remove ${event.eventName}`"
          :aria-expanded="confirming"
          :aria-controls="confirmId"
          :disabled="busy"
          @click="openConfirm"
        >
          <PhTrash weight="bold" class="size-4" aria-hidden="true" />
        </button>

        <div
          v-if="confirming"
          :id="confirmId"
          data-cart-confirm
          class="grid gap-4 rounded-xl emphasis-floating p-4 text-pretty"
          role="dialog"
          :aria-labelledby="confirmLabelId"
        >
          <p :id="confirmLabelId" class="text-ui text-pretty text-strong">
            Remove all tickets for this event?
          </p>
          <div class="flex gap-2">
            <button
              type="button"
              class="is-interactive btn btn-sm flex-1 emphasis-normal intent-neutral"
              @click="closeConfirm"
            >
              Cancel
            </button>
            <button
              type="button"
              class="is-interactive btn btn-sm flex-1 emphasis-strong intent-danger"
              :disabled="busy"
              @click="confirmRemove"
            >
              Remove
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="grid gap-3 pl-6">
      <div
        v-for="ticket in event.tickets"
        :key="ticket.name"
        class="grid gap-2"
      >
        <div class="md:hidden">
          <p class="text-ui font-medium text-strong">{{ ticket.name }}</p>
        </div>
        <div class="flex items-center rounded-lg bg-sunken px-3 py-2">
          <div class="hidden min-w-0 flex-1 pr-4 md:block">
            <span class="block truncate text-ui font-medium text-strong">
              {{ ticket.name }}
            </span>
          </div>
          <span class="w-20 shrink-0 text-ui-meta text-subtle">
            {{ ticket.priceEach === 0 ? 'Free' : money(ticket.priceEach) }}
          </span>
          <div class="flex flex-1 items-center justify-center">
            <span class="shrink-0 text-ui-meta font-medium text-strong">
              &times; {{ ticket.quantity }}
            </span>
          </div>
          <span
            class="w-24 shrink-0 text-right text-ui font-bold text-strong tabular-nums"
          >
            {{ money(ticket.quantity * ticket.priceEach) }}
          </span>
        </div>
      </div>
    </div>
  </div>
</template>
