// packages/widgets/src/cart-drawer/react/CartUrgencyBadge.tsx
'use client'

import { type CSSProperties, useEffect, useRef, useState } from 'react'

import NumberFlow from '@number-flow/react'

import { Badge } from '@oztix/roadie-components'
import { cn } from '@oztix/roadie-core/utils'

import { URGENCY_LONG_FORMAT_S, urgencyLevel } from '../core'
import { useCountdown } from './useCountdown'

// Coarse so the live region doesn't announce every second.
function coarseUrgencyMessage(remaining: number | null): string {
  const level = urgencyLevel(remaining)
  if (level === 'expired') return 'Cart expired'
  if (remaining === null) return ''
  if (level === 'danger') return 'Cart expiring soon'
  const minutes = Math.ceil(remaining / 60)
  return `${minutes} ${minutes === 1 ? 'minute' : 'minutes'} remaining to checkout`
}

type CartUrgencyBadgeProps = {
  ticketCount: number
  expiresAtUtc: string | undefined
  /** Drawer open-state progress 0..1. Controls the tail expansion. */
  progress?: number
  /** Fires the animate-pop cue once per add. */
  bounce?: boolean
  className?: string
  style?: CSSProperties
}

export function CartUrgencyBadge({
  ticketCount,
  expiresAtUtc,
  progress = 0,
  bounce = false,
  className,
  style
}: CartUrgencyBadgeProps) {
  const remaining = useCountdown(expiresAtUtc)

  const level = urgencyLevel(remaining)
  const intent: 'success' | 'warning' | 'danger' =
    level === 'expired' ? 'danger' : level

  // Announce only at coarse transitions, not every second.
  const minuteBucket = remaining === null ? null : Math.ceil(remaining / 60)
  const [announcement, setAnnouncement] = useState('')
  const lastKeyRef = useRef<string | null>(null)
  useEffect(() => {
    const key = `${level}:${minuteBucket}`
    if (key === lastKeyRef.current) return
    lastKeyRef.current = key
    setAnnouncement(coarseUrgencyMessage(remaining))
  }, [level, minuteBucket, remaining])

  const tailMaxWidth = Math.max(0, Math.min(1, progress)) * 200
  const tailOpacity = Math.max(0, Math.min(1, progress))

  const showCountdown = remaining !== null && remaining > 0

  return (
    <Badge
      intent={intent}
      emphasis='subtle'
      size='sm'
      indicator={showCountdown}
      indicatorPulse={showCountdown}
      className={cn('gap-2 px-3 py-1', bounce && 'animate-pop', className)}
      style={style}
    >
      <span className='sr-only' aria-live='polite' aria-atomic='true'>
        {announcement}
      </span>
      <NumberFlow value={ticketCount} className='tabular-nums' />{' '}
      {ticketCount === 1 ? 'ticket' : 'tickets'}
      {showCountdown && remaining !== null && (
        <>
          {remaining > URGENCY_LONG_FORMAT_S ? (
            <span className='tabular-nums'>
              <NumberFlow value={Math.ceil(remaining / 60)} suffix=' mins' />
            </span>
          ) : (
            <span className='tabular-nums'>
              <NumberFlow value={Math.floor(remaining / 60)} />
              :
              <NumberFlow
                value={remaining % 60}
                format={{ minimumIntegerDigits: 2 }}
              />
            </span>
          )}
          <span
            className='overflow-hidden whitespace-nowrap'
            style={{
              maxWidth: tailMaxWidth,
              opacity: tailOpacity,
              transition: 'max-width 300ms ease-out, opacity 300ms ease-out'
            }}
          >
            remaining to checkout
          </span>
        </>
      )}
    </Badge>
  )
}

// packages/widgets/src/cart-drawer/vue/CartUrgencyBadge.vue
<script setup lang="ts">
import NumberFlow from '@number-flow/vue'
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'

import { URGENCY_LONG_FORMAT_S, remainingSeconds, urgencyLevel } from '../core'

const PAD2_FORMAT = { minimumIntegerDigits: 2 }

const props = withDefaults(
  defineProps<{
    ticketCount: number
    expiresAtUtc: string | undefined
    /** Drawer open progress 0..1. */
    progress?: number
    /** Fires the animate-pop cue once per add. */
    bounce?: boolean
  }>(),
  { progress: 0, bounce: false }
)

const now = ref(Date.now())
let timer: ReturnType<typeof setInterval> | null = null
onMounted(() => {
  timer = setInterval(() => {
    now.value = Date.now()
  }, 1000)
})
onBeforeUnmount(() => {
  if (timer !== null) clearInterval(timer)
})

const remaining = computed(() =>
  remainingSeconds(props.expiresAtUtc, now.value)
)
const level = computed(() => urgencyLevel(remaining.value))
const intent = computed(() =>
  level.value === 'expired' ? 'danger' : level.value
)
const showCountdown = computed(
  () => remaining.value !== null && remaining.value > 0
)
const isLongFormat = computed(
  () => (remaining.value ?? 0) > URGENCY_LONG_FORMAT_S
)
const minutesCeil = computed(() => Math.ceil((remaining.value ?? 0) / 60))
const minutesFloor = computed(() => Math.floor((remaining.value ?? 0) / 60))
const secondsPart = computed(() => (remaining.value ?? 0) % 60)
const ticketLabel = computed(() =>
  props.ticketCount === 1 ? 'ticket' : 'tickets'
)

const coarseMessage = computed(() => {
  if (level.value === 'expired') return 'Cart expired'
  if (remaining.value === null) return ''
  if (level.value === 'danger') return 'Cart expiring soon'
  const minutes = Math.ceil(remaining.value / 60)
  return `${minutes} ${minutes === 1 ? 'minute' : 'minutes'} remaining to checkout`
})
const minuteBucket = computed(() =>
  remaining.value === null ? null : Math.ceil(remaining.value / 60)
)
const announcement = ref('')
watch(
  () => `${level.value}:${minuteBucket.value}`,
  () => {
    announcement.value = coarseMessage.value
  },
  { immediate: true }
)
</script>

<template>
  <span
    class="inline-flex items-center justify-center gap-2 rounded-full emphasis-subtle px-3 py-1 text-xs font-semibold whitespace-nowrap text-subtle [&_svg]:size-[1em] [&_svg]:shrink-0"
    :class="[`intent-${intent}`, { 'animate-pop': bounce }]"
    :data-intent="intent"
  >
    <span class="sr-only" aria-live="polite" aria-atomic="true">
      {{ announcement }}
    </span>
    <span
      v-if="showCountdown"
      aria-hidden="true"
      class="size-1.5 shrink-0 rounded-full bg-current"
      :class="{ 'animate-pulse': showCountdown }"
    />
    <span class="tabular-nums" data-testid="cart-badge-count">
      <NumberFlow :value="ticketCount" />
    </span>
    {{ ticketLabel }}
    <template v-if="showCountdown">
      <span class="tabular-nums" data-testid="cart-badge-time">
        <NumberFlow v-if="isLongFormat" :value="minutesCeil" suffix=" mins" />
        <template v-else>
          <NumberFlow :value="minutesFloor" />:<NumberFlow
            :value="secondsPart"
            :format="PAD2_FORMAT"
          />
        </template>
      </span>
      <span
        class="overflow-hidden whitespace-nowrap transition-[max-width,opacity] duration-300 ease-out"
        :style="{
          maxWidth: `${Math.max(0, Math.min(1, progress)) * 200}px`,
          opacity: Math.max(0, Math.min(1, progress))
        }"
      >
        remaining to checkout
      </span>
    </template>
  </span>
</template>
