// packages/widgets/src/cart-drawer/react/CartExpiryModals.tsx
'use client'

import NumberFlow from '@number-flow/react'
import { ClockIcon } from '@phosphor-icons/react'

import { Button } from '@oztix/roadie-components'

import { CartExpiryModal } from './CartExpiryModal'

export type CartExpiryModalsProps = {
  showWarning: boolean
  expired: boolean
  remaining: number | null
  onDismissWarning: () => void
  checkoutUrl: string | null
  browseHref: string
  onNavigate: (href: string) => void
}

export function CartExpiryModals({
  showWarning,
  expired,
  remaining,
  onDismissWarning,
  checkoutUrl,
  browseHref,
  onNavigate
}: CartExpiryModalsProps) {
  const mins = Math.floor((remaining ?? 0) / 60)
  const secs = (remaining ?? 0) % 60

  return (
    <>
      <CartExpiryModal
        open={showWarning && !expired}
        dismissible
        onClose={onDismissWarning}
        title='Still here?'
        icon={
          <div className='flex size-14 items-center justify-center rounded-full bg-subtle'>
            <ClockIcon
              weight='bold'
              className='size-7 text-normal intent-danger'
            />
          </div>
        }
        actions={
          <>
            <Button
              emphasis='normal'
              intent='neutral'
              className='flex-1'
              onClick={onDismissWarning}
            >
              Keep browsing
            </Button>
            <Button
              emphasis='strong'
              intent='accent'
              className='flex-1'
              disabled={!checkoutUrl}
              onClick={() => {
                if (checkoutUrl) onNavigate(checkoutUrl)
              }}
            >
              Checkout
            </Button>
          </>
        }
      >
        Your tickets are held for a little longer. Check out now to secure them.
        <span className='mt-2 block text-display-ui-4 text-normal tabular-nums intent-danger'>
          <NumberFlow value={mins} />:
          <NumberFlow value={secs} format={{ minimumIntegerDigits: 2 }} />
        </span>
      </CartExpiryModal>

      <CartExpiryModal
        open={expired}
        title='Your hold has ended'
        icon={
          <div className='flex size-16 items-center justify-center rounded-full bg-subtle'>
            <ClockIcon weight='bold' className='size-8 text-subtler' />
          </div>
        }
        actions={
          <Button
            emphasis='strong'
            intent='accent'
            className='flex-1'
            onClick={() => onNavigate(browseHref)}
          >
            Browse events
          </Button>
        }
      >
        Your tickets are no longer being held. Head back to browse and grab them
        again.
      </CartExpiryModal>
    </>
  )
}

// packages/widgets/src/cart-drawer/vue/CartExpiryModals.vue
<script setup lang="ts">
import NumberFlow from '@number-flow/vue'
import { PhClock } from '@phosphor-icons/vue'
import { computed, useId } from 'vue'

import CartExpiryModal from './CartExpiryModal.vue'

const props = defineProps<{
  showWarning: boolean
  expired: boolean
  /** Seconds remaining. */
  remaining: number | null
  onDismissWarning: () => void
  /** Checkout target; null while loading. */
  checkoutUrl: string | null
  /** Collection page target. */
  browseHref: string
  onNavigate: (href: string) => void
}>()

const warningTitleId = useId()
const expiredTitleId = useId()
const PAD2_FORMAT = { minimumIntegerDigits: 2 }
const minutes = computed(() => Math.floor((props.remaining ?? 0) / 60))
const seconds = computed(() => (props.remaining ?? 0) % 60)

function checkout() {
  if (props.checkoutUrl) props.onNavigate(props.checkoutUrl)
}
function browse() {
  props.onNavigate(props.browseHref)
}
</script>

<template>
  <CartExpiryModal
    v-if="showWarning && !expired"
    :title-id="warningTitleId"
    title="Still here?"
    dismissible
    :on-close="onDismissWarning"
  >
    <template #icon>
      <div
        class="flex size-14 items-center justify-center rounded-full bg-subtle"
      >
        <PhClock
          weight="bold"
          class="size-7 text-[var(--intent-9)] intent-danger"
          aria-hidden="true"
        />
      </div>
    </template>
    <template #body>
      Your tickets are held for a little longer. Check out now to secure them.
      <span
        class="mt-2 block text-display-ui-4 text-[var(--intent-9)] tabular-nums intent-danger"
      >
        <NumberFlow :value="minutes" />:<NumberFlow
          :value="seconds"
          :format="PAD2_FORMAT"
        />
      </span>
    </template>
    <template #actions>
      <button
        type="button"
        class="is-interactive btn btn-md flex-1 emphasis-normal intent-neutral"
        @click="onDismissWarning"
      >
        Keep browsing
      </button>
      <button
        type="button"
        class="is-interactive btn btn-md flex-1 emphasis-strong intent-danger"
        :disabled="!checkoutUrl"
        @click="checkout"
      >
        Checkout
      </button>
    </template>
  </CartExpiryModal>

  <!-- Blocking; no dismiss — the only exit is back to browsing. -->
  <CartExpiryModal
    v-if="expired"
    :title-id="expiredTitleId"
    title="Your hold has ended"
  >
    <template #icon>
      <div
        class="flex size-16 items-center justify-center rounded-full bg-subtle"
      >
        <PhClock weight="bold" class="size-8 text-subtler" aria-hidden="true" />
      </div>
    </template>
    <template #body>
      Your tickets are no longer being held. Head back to browse and grab them
      again.
    </template>
    <template #actions>
      <button
        type="button"
        class="is-interactive btn btn-md flex-1 emphasis-strong intent-accent"
        @click="browse"
      >
        Browse events
      </button>
    </template>
  </CartExpiryModal>
</template>
